import React, { useEffect, useRef, useState } from 'react';
import { Garment } from './components.jsx';
import { beginFavorite, claimFavorite, closetCheck, daysSinceWear, favoriteProgress, matchInspiration } from './journey.js';
import { api, preparePhoto, imageData } from './photos.js';
import { categories } from './logic.js';

export function ClosetCheck({state,save,onStyle,onListing}) {
  const items=closetCheck(state.items);
  return <section className="closet-check"><div className="section-heading"><div><p className="eyebrow">A SECOND LOOK</p><h2>Your closet check</h2><p>Pieces with no recorded wear for at least 30 days.</p></div></div>
    {items.length?<div className="check-grid">{items.map(item=><article className="check-card" key={item.id}><div className="check-photo"><Garment item={item}/></div><div><span className="age-label">{daysSinceWear(item)} days {item.lastWorn?'since last wear':'since added'}</span><h3>{item.name}</h3><p>{item.category} · {item.colorName || 'Color not recorded'}</p><div className="toolbar"><button className="primary" onClick={()=>onStyle(item)}>Style it</button><button onClick={()=>save(s=>({...s,items:s.items.map(i=>i.id===item.id?{...i,keepUntil:new Date(Date.now()+30*86400000).toISOString()}:i)}))}>Keep for now</button><button onClick={()=>onListing(item)}>Resell</button></div></div></article>)}</div>:<div className="notice">No pieces are due for a closet check. Keep recording wears to build your history.</div>}
    <p className="muted">Keep for now pauses the reminder for 30 days. Unrecorded wears are unknown, not proof an item was never worn.</p>
    {state.items.some(i=>Date.parse(i.keepUntil)>Date.now())&&<button className="text-button" onClick={()=>save(s=>({...s,items:s.items.map(({keepUntil,...i})=>i)}))}>Show kept pieces again</button>}
  </section>;
}

export function FavoriteQuest({state,save,onStyle}) {
  const [chosen,setChosen]=useState(state.favoriteQuest?.anchorId||'');
  const anchor=state.items.find(i=>i.id===state.favoriteQuest?.anchorId);
  const looks=favoriteProgress(state),complete=state.completed.includes('forgotten-favorite');
  return <section className="favorite-quest"><div className="favorite-intro"><p className="eyebrow">THE FORGOTTEN FAVORITE</p><h2>One piece.<br/>Three fresh ways.</h2><p>Save three different outfits around one piece you want to rediscover. Changing only an accessory doesn’t count.</p><strong className="quest-reward">{complete?'✓ 150 XP earned':'+150 XP'}</strong>
    {!anchor&&!complete?<><label>Your forgotten favorite<select value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a piece</option>{state.items.filter(i=>!i.needsReview).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><button className="primary" disabled={!chosen} onClick={()=>save(s=>beginFavorite(s,chosen))}>Accept challenge</button></>:anchor&&<div className="quest-anchor"><Garment item={anchor}/><div><strong>{anchor.name}</strong><p>{looks.length} of 3 outfits saved</p>{!complete&&<button className="primary" onClick={()=>onStyle(anchor)}>Create another look</button>}</div></div>}
    <progress value={looks.length} max="3" aria-label="Forgotten favorite progress"/>{!complete&&<button disabled={looks.length<3} onClick={()=>save(claimFavorite)}>Complete quest · earn 150 XP</button>}
  </div><div className="quest-looks">{[0,1,2].map(index=><article key={index} className={looks[index]?'quest-look complete':'quest-look'}><span>{looks[index]?'✓':'0'+(index+1)}</span><div><h3>{looks[index]?.title||['Your first combination','A different occasion','One more way'][index]}</h3>{looks[index]?<div className="quest-miniatures">{looks[index].itemIds.map(id=>state.items.find(i=>i.id===id)).filter(Boolean).map(item=><Garment key={item.id} item={item}/>)}</div>:<p>Save a complete look with your chosen piece.</p>}</div></article>)}</div></section>;
}

export function Inspiration({state,save,onStyle,ready}) {
  const [image,setImage]=useState(''),[summary,setSummary]=useState(''),[pieces,setPieces]=useState([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[source,setSource]=useState('manual'),[model,setModel]=useState('');
  const run=useRef(0), fileRef=useRef(null), controller=useRef(null);
  useEffect(()=>()=>{run.current++;controller.current?.abort();},[]);
  const matches=matchInspiration(pieces,state.items);
  async function upload(file){if(!file)return;const id=++run.current;setBusy(true);setMessage('');try{const photo=await preparePhoto(file);if(id!==run.current)return;setImage(photo);setPieces([]);setSummary('');setSource('manual');setModel('');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  async function analyze(){setBusy(true);setMessage('Reading the visible outfit ideas…');const id=++run.current;controller.current=new AbortController();try{const result=await api('inspiration',{image:await imageData(image)},'POST',{timeoutMs:65000,signal:controller.current.signal});if(id!==run.current)return;setPieces(result.data.pieces);setSummary(result.data.summary);setSource('local-photo-analysis');setModel(result.model);setMessage('Review the ideas below. Matches use your saved garment details.');}catch(e){if(id===run.current)setMessage(e.message);}finally{if(id===run.current)setBusy(false);}}
  function saveIdea(){if(!pieces.length)return;const saved=save(s=>({...s,inspirations:[...(s.inspirations||[]),{id:crypto.randomUUID(),image,summary,pieces,source,model,createdAt:new Date().toISOString()}]}));if(saved)setMessage('Inspiration saved on this device.');}
  return <><div className="inspiration-workspace"><section className="inspiration-source"><div className="inspiration-photo">{image?<img src={image} alt="Your outfit inspiration"/>:<div><span>＋</span><h2>A look you love</h2><p>Add a photo or describe its pieces.</p></div>}</div><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" aria-label="Inspiration photo" onChange={e=>upload(e.target.files[0])}/><div className="toolbar"><button disabled={busy} onClick={()=>fileRef.current.click()}>Choose inspiration photo</button><button disabled={busy} onClick={()=>{setImage('photos/trousers.jpg');setSummary('');setPieces([]);setSource('manual');setModel('');setMessage('Sample style photograph by Ed Yourdon / Themightyquill, CC BY-SA 2.0. Photo credits are under More.');}}>Try a sample photo</button>{busy&&<button onClick={()=>{run.current++;controller.current?.abort();setBusy(false);setMessage('Stopped. Your photo is ready when you want to try again.');}}>Stop analysis</button>}{image&&<button className="primary" disabled={busy||!ready} onClick={analyze}>{busy?'Reading photo…':'Find the style ideas'}</button>}</div><p className="muted">{image==='photos/trousers.jpg'&&<>Sample photograph: Ed Yourdon / Themightyquill, CC BY-SA 2.0. Credits under More.<br/></>}{ready?'Photo analysis runs locally. You review its suggestions.':'Local photo analysis is offline. You can still describe and match the pieces.'}</p></section>
    <section className="inspiration-ideas"><p className="eyebrow">RECREATE THE IDEA</p><h2>Your closet comes first.</h2><label>What caught your eye?<input maxLength="160" value={summary} disabled={busy} onChange={e=>setSummary(e.target.value)} placeholder="Relaxed layers with a tailored jacket"/></label><div className="inspiration-pieces">{pieces.map((piece,index)=><div className="inspiration-piece" key={index}><label>Piece {index+1}<select disabled={busy} value={piece.category} onChange={e=>setPieces(p=>p.map((v,i)=>i===index?{...v,category:e.target.value}:v))}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Style idea<input disabled={busy} maxLength="160" value={piece.description} onChange={e=>setPieces(p=>p.map((v,i)=>i===index?{...v,description:e.target.value}:v))}/></label><label>Color<input disabled={busy} maxLength="160" value={piece.color} onChange={e=>setPieces(p=>p.map((v,i)=>i===index?{...v,color:e.target.value}:v))}/></label><button disabled={busy} aria-label={`Remove idea ${index+1}`} onClick={()=>setPieces(p=>p.filter((_,i)=>i!==index))}>×</button></div>)}</div><button disabled={busy||pieces.length>=6} onClick={()=>setPieces(p=>[...p,{category:'Top',description:'',color:''}])}>＋ Add a style idea</button>{message&&<p role="status">{message}</p>}{pieces.length>0&&<div className="toolbar"><button className="primary" disabled={busy||pieces.some(p=>!p.description.trim()||!p.color.trim())} onClick={saveIdea}>Save inspiration</button><button disabled={busy} onClick={()=>onStyle(`${summary}. ${pieces.map(p=>`${p.color} ${p.description}`).join('. ')}`,matches.find(m=>m.item?.category==='Outerwear')?.item)}>Style these ideas</button></div>}</section></div>
    {pieces.length>0&&<section className="inspiration-matches"><div className="section-heading"><div><h2>Already in your closet</h2><p>Same-category alternatives ranked by words in your reviewed garment details.</p></div></div><div className="match-grid">{matches.map((match,i)=><article key={i}>{match.item?<><Garment item={match.item}/><p>{match.description}</p><h3>{match.item.name}</h3><small>{match.exactTerms?'Related details in your closet':'Category alternative · compare the details'}</small></>:<div className="missing-piece"><h3>{match.category}</h3><p>No reviewed match yet. Try another idea or add a piece.</p></div>}</article>)}</div><p className="muted">{source==='local-photo-analysis'?`Photo ideas suggested by ${model}.`:'Ideas entered manually.'} Matches are alternatives, not exact visual copies.</p></section>}
    {(state.inspirations||[]).length>0&&<section><h2>Saved inspiration</h2><div className="saved-inspirations">{state.inspirations.map(idea=><button key={idea.id} disabled={busy} onClick={()=>{setImage(idea.image);setSummary(idea.summary);setPieces(idea.pieces);setSource(idea.source);setModel(idea.model||'');setMessage('Saved idea opened. Matches reflect your current closet.');}}>{idea.image&&<img src={idea.image} alt="Saved outfit inspiration"/>}<span>{idea.summary||'Outfit inspiration'}</span></button>)}</div></section>}</>;
}
