import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { categories, contexts, quests, initialState, recommend, completeQuest, markWorn, listing } from './logic.js';
import './style.css';

const KEY = 'closet-quest-demo-v1';
function load() {
  try { const value = JSON.parse(localStorage.getItem(KEY)); if (value && Array.isArray(value.items) && Array.isArray(value.completed) && Array.isArray(value.submissions) && Number.isFinite(value.xp) && typeof value.profile === 'string') return value; } catch {}
  return initialState();
}
function Garment({ item }) {
  if (item.image) return <img className="garment-photo" src={item.image} alt={item.name}/>;
  const paths = {
    Top: 'M63 35 38 46 17 78 44 95 58 76 58 158 142 158 142 76 156 95 183 78 162 46 137 35Q100 60 63 35Z',
    Bottom: 'M59 32H141L150 169H109L100 86 91 169H50Z',
    Shoes: 'M43 77 75 87 93 63 112 83 125 116 165 128Q183 134 180 152H25V125Z',
    Outerwear: 'M66 30 38 46 19 151 48 159 61 92 59 171H141L139 92 152 159 181 151 162 46 134 30 100 65Z',
    Dress: 'M73 27H88Q100 43 112 27H127L133 72 119 87 162 174H38L81 87 67 72Z',
    Accessory: 'M59 74V60A41 41 0 0 1 141 60V74H159L168 165H32L41 74ZM76 74H124V60A24 24 0 0 0 76 60Z',
  };
  return <svg className="garment" viewBox="0 0 200 200" role="img" aria-label={item.name}><ellipse cx="100" cy="184" rx="51" ry="5" fill="#000" opacity=".06"/><path d={paths[item.category]} fill={item.color} stroke="#253c36" strokeWidth="1.5" strokeLinejoin="round"/>{item.category === 'Top' && <path d="M83 44Q100 75 117 44M65 150H135" fill="none" stroke="#253c36" opacity=".25"/>}{item.category === 'Bottom' && <path d="M61 47H140M100 48V84M62 51Q82 72 85 49" fill="none" stroke="#fff" opacity=".4"/>}{item.category === 'Outerwear' && <path d="M66 30 88 100 100 65 112 100 134 30M100 100V170" fill="none" stroke="#fff" opacity=".35"/>}{item.category === 'Shoes' && <path d="M27 141H176M90 86 113 91M97 99 118 104M102 111 122 115" stroke="#fff" fill="none" strokeWidth="4"/>}</svg>;
}
function App() {
  const [state, setState] = useState(load), [page, setPage] = useState('Closet'), [filter, setFilter] = useState('All'), [search, setSearch] = useState('');
  const [context, setContext] = useState(contexts[0]), [outfitIds, setOutfitIds] = useState([]), [variation, setVariation] = useState(0), [questId, setQuestId] = useState('rediscover');
  const [editor, setEditor] = useState(null), [resale, setResale] = useState(null), [toast, setToast] = useState(''), [busy, setBusy] = useState(false), [worn, setWorn] = useState(false);
  function notify(text) { setToast(text); }
  function save(next) {
    try { localStorage.setItem(KEY, JSON.stringify(next)); setState(next); return true; }
    catch { notify('Could not save: browser storage is full or unavailable. Try a smaller photo or delete an item.'); return false; }
  }
  const outfit = outfitIds.map(id => state.items.find(i => i.id === id)).filter(Boolean);
  const selectedQuest = quests.find(q => q.id === questId);
  const lowUse = state.items.filter(i => i.wears <= 1);
  function generate(nextContext = context, nextVariation = variation) {
    const result = recommend(state.items, nextContext, nextVariation);
    setOutfitIds(result.map(i => i.id)); setWorn(false); setVariation(nextVariation + 1);
    if (!result.length) notify('Add a top and bottom (or a dress), plus shoes to build an outfit.');
  }
  function startQuest(q) { setQuestId(q.id); setContext(q.context); setPage('Outfits'); generate(q.context, 0); }
  function openListing(item) { setResale({ id: item.id, text: listing(item) }); }
  async function upload(file) {
    if (!file) return;
    if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 8 * 1024 * 1024) { notify('Choose a JPG, PNG, or WebP image under 8 MB.'); return; }
    setBusy(true);
    try {
      const url = URL.createObjectURL(file), image = new Image();
      try {
        image.src = url; await image.decode();
        const canvas = document.createElement('canvas'), scale = Math.min(1, 700 / Math.max(image.width, image.height));
        canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale));
        canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height);
        const name = file.name.replace(/\.[^.]+$/, '').replace(/[-_]/g, ' ').slice(0,80);
        const category = /jean|pant|trouser|skirt/i.test(name) ? 'Bottom' : /shoe|sneaker|boot/i.test(name) ? 'Shoes' : /dress/i.test(name) ? 'Dress' : /jacket|blazer|coat/i.test(name) ? 'Outerwear' : 'Top';
        setEditor(current => current ? { ...current, name: current.name || name, category: current.isNew ? category : current.category, image: canvas.toDataURL('image/jpeg', .8) } : null);
      } finally { URL.revokeObjectURL(url); }
    } catch { notify('This image could not be opened. Try another photo.'); }
    finally { setBusy(false); }
  }
  function removeItem(id) {
    if (save({ ...state, items: state.items.filter(i => i.id !== id), submissions: state.submissions.map(s => ({...s, itemIds: s.itemIds.filter(itemId => itemId !== id)})) })) {
      setOutfitIds([]); setEditor(null); notify('Garment and its photo deleted from this browser.');
    }
  }
  function exportListing() {
    const item = state.items.find(i => i.id === resale.id);
    const blob = new Blob([JSON.stringify({ title: item.name, description: resale.text, category: item.category, color: item.color, tags: item.tags, image: item.image || null, imageNote: item.image ? 'Original resized photo; background not removed.' : 'Illustration only; add a real photo before publishing.' }, null, 2)], {type:'application/json'});
    const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = 'closet-quest-listing.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); notify('Listing package exported. Review it before publishing.');
  }
  return <div className="app">
    <aside className="sidebar"><a className="brand" href="#" onClick={e => {e.preventDefault(); setPage('Closet');}}><span className="brand-icon">cq</span><span>closet quest<span className="brand-sub">LESS NEW. MORE YOU.</span></span></a><div className="nav-label">YOUR LITTLE STYLE WORLD</div><nav>{[['Closet','▦'],['Outfits','✧'],['Quests','⚑'],['Resale','↗']].map(([name,icon]) => <button key={name} className={page === name ? 'nav active' : 'nav'} onClick={() => setPage(name)}><span>{icon}</span>{name}{name === 'Quests' && <small>{quests.length-state.completed.length}</small>}</button>)}</nav><div className="sidebar-note"><span>↻</span><h3>Good style goes around.</h3><p>Your next favorite outfit might already be in your closet.</p></div><button className="profile" onClick={() => { const name = prompt('Name for your local demo profile', state.profile || 'Alex'); if (name?.trim()) save({...state, profile:name.trim().slice(0,40)}); }}><span className="avatar">{(state.profile || 'A')[0].toUpperCase()}</span><span>{state.profile || 'Alex’s demo closet'}<small>Local demo profile · edit</small></span></button></aside>
    <main><header><span>YOUR WARDROBE, REIMAGINED</span><div className="level">✦ Level {Math.floor(state.xp/100)+1} <b>{state.xp} XP</b></div></header>
      <div className="page-heading"><div><p className="eyebrow">MAKE MORE OF WHAT YOU OWN</p><h1>{ {Closet:'A closet full of possibilities.',Outfits:'Your next great combination.',Quests:'A little challenge. A fresh look.',Resale:'Ready for a second chapter.'}[page] }</h1><p>{ {Closet:'Old favorites. New combinations. All you.',Outfits:'Outfits made from your clothes, for your kind of day.',Quests:'Rediscover your wardrobe, one quest at a time.',Resale:'Give the pieces you reach for less a new beginning.'}[page] }</p></div>{page === 'Closet' && <button className="primary" onClick={() => setEditor({id:crypto.randomUUID(),name:'',category:'Top',color:'#a0a18f',tags:'Campus casual',wears:0,isNew:true})}>＋ Add a garment</button>}</div>
      {page === 'Closet' && <><section className="hero"><div><span className="pill">YOUR DAILY STYLE SIDE QUEST</span><h2>New outfit.<br/>Same lovely closet.</h2><p>Give a forgotten favorite its main-character moment.</p><button className="primary light" onClick={() => startQuest(quests[0])}>Take the hidden gem quest <span>↗</span></button></div><div className="hero-art" aria-hidden="true"><div className="art-card left"><Garment item={state.items.find(i => i.category === 'Top') || initialState().items[0]}/></div><div className="art-card right"><Garment item={state.items.find(i => i.category === 'Bottom') || initialState().items[1]}/></div><span className="spark">✧</span><span className="art-label">already yours. newly styled.</span></div></section><section className="stats"><div><strong>{state.items.length}</strong><span>pieces, endless possibilities</span></div><div><strong>{state.items.reduce((sum,i) => sum+i.wears,0)}</strong><span>recorded wears</span></div><div><strong>{lowUse.length}</strong><span>waiting to be rediscovered</span></div></section><div className="section-heading"><h2>Your wardrobe <small>{state.items.length} pieces</small></h2><label className="search"><span>⌕</span><input aria-label="Search wardrobe" placeholder="Find a favorite…" value={search} onChange={e => setSearch(e.target.value)}/></label></div><div className="filters">{['All',...categories].map(c => <button key={c} className={filter === c ? 'selected' : ''} onClick={() => setFilter(c)}>{c}</button>)}</div><div className="grid">{state.items.filter(i => (filter === 'All' || i.category === filter) && `${i.name} ${i.tags}`.toLowerCase().includes(search.toLowerCase())).map(item => <button className="item-card" key={item.id} onClick={() => setEditor({...item})}><div className="item-visual"><span className="item-tag">{item.wears <= 1 ? 'Rediscover me' : `${item.wears} wears`}</span><Garment item={item}/><span className="edit-hint">Edit ↗</span></div><div className="item-info"><h3>{item.name}</h3><p><span className="color-dot" style={{background:item.color}}/>{item.category}<span>{item.wears} wears</span></p></div></button>)}</div>{!state.items.some(i => (filter === 'All' || i.category === filter) && `${i.name} ${i.tags}`.toLowerCase().includes(search.toLowerCase())) && <div className="empty">No garments here yet. Add a piece or change your search.</div>}</>}
      {page === 'Outfits' && <><section className="panel"><div className="section-heading"><div><h2>What’s on your agenda?</h2><p>Simple rules favor matching style tags and less-worn pieces.</p></div></div><div className="toolbar"><label>Styling context<select value={context} onChange={e => {setContext(e.target.value);setOutfitIds([]);setVariation(0);}}>{contexts.map(c => <option key={c}>{c}</option>)}</select></label><button className="primary" onClick={() => generate()}>{outfit.length ? 'Try another combination ↻' : 'Build my outfit ✧'}</button></div></section>{outfit.length ? <><div className="grid outfit-grid">{outfit.map(item => <div className="item-card" key={item.id}><div className="item-visual"><Garment item={item}/></div><div className="item-info"><h3>{item.name}</h3><p>{item.category} · {item.wears} wears</p></div></div>)}</div><section className="panel"><h2>A fresh take on your favorites</h2><p>Built entirely from your wardrobe. Try another combination to rotate through your options.</p><div className="toolbar"><button className="primary" disabled={worn} onClick={() => {if(save(markWorn(state,outfitIds))) {setWorn(true);notify('Outfit marked as worn. Every piece got +1 wear.');}}}>{worn ? '✓ Wear recorded' : 'Mark outfit as worn'}</button><label>Submit to quest<select value={questId} onChange={e => setQuestId(e.target.value)}>{quests.map(q => <option key={q.id} value={q.id}>{q.title} · {q.xp} XP</option>)}</select></label><button disabled={state.completed.includes(questId)} onClick={() => {try {if(save(completeQuest(state,selectedQuest,outfit,context))) notify(`Quest complete! +${selectedQuest.xp} XP`);}catch(error){notify(error.message);}}}>{state.completed.includes(questId) ? '✓ Quest completed' : 'Submit outfit + earn XP'}</button></div><p className="muted">Quest: {selectedQuest.subtitle} Context: {selectedQuest.context}. Each quest rewards XP once.</p></section></> : <div className="empty">✧<h2>Your wardrobe has ideas.</h2><p>Choose a context and build your first outfit.</p></div>}</>}
      {page === 'Quests' && <><section className="progress-panel"><div><p className="eyebrow">YOUR STYLE JOURNEY</p><h2>Level {Math.floor(state.xp/100)+1} · Closet explorer</h2><p>{state.xp} total XP · {100-state.xp%100} XP to the next level</p></div><progress max="100" value={state.xp%100} aria-label="Progress to next level"/></section><div className="quest-grid">{quests.map((q,index) => <section className="quest-card" key={q.id}><div className="quest-top"><span>0{index+1} / STYLE QUEST</span><b>+{q.xp} XP</b></div><div className="quest-symbol">{['✧','☕','↗'][index]}</div><h2>{q.title}</h2><p>{q.subtitle}</p><small>{q.context}</small><button className="primary" disabled={state.completed.includes(q.id)} onClick={() => startQuest(q)}>{state.completed.includes(q.id) ? '✓ Completed' : 'Start quest ↗'}</button></section>)}</div></>}
      {page === 'Resale' && <><div className="notice">↻ These pieces have one recorded wear or less. Keep exploring them, or prepare a listing for a new owner.</div><div className="grid">{lowUse.map(item => <div className="item-card" key={item.id}><div className="item-visual"><Garment item={item}/></div><div className="item-info"><h3>{item.name}</h3><p>{item.wears} recorded wears</p><button onClick={() => openListing(item)}>Prepare listing ↗</button></div></div>)}</div>{!lowUse.length && <div className="empty">Every piece has more than one recorded wear. You can still prepare a listing from any garment’s edit screen.</div>}</>}
      <footer><span>closet quest</span><p>Frontend demo · saved in this browser · no real AI or account authentication</p></footer>
    </main>
    {toast && <div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}>×</button></div>}
    {editor && <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="editor-title"><div className="section-heading"><h2 id="editor-title">{editor.isNew ? 'Meet your next favorite.' : 'Make it your own.'}</h2><button aria-label="Close garment editor" onClick={() => setEditor(null)}>×</button></div><form onSubmit={e => {e.preventDefault(); const {isNew,...item}=editor; if(!item.name.trim())return; item.name=item.name.trim(); if(save({...state,items:isNew?[...state.items,item]:state.items.map(i=>i.id===item.id?item:i)})) {setEditor(null);setOutfitIds([]);notify(isNew?'New garment added to your closet.':'Garment updated.');}}}><div className="upload-area"><Garment item={editor}/><label className="upload-label">{busy?'Preparing photo…':'Choose garment photo'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e => upload(e.target.files[0])}/></label></div><p className="muted">Demo assistance uses the filename to suggest a category. Review every field. Photos are resized locally; background removal and AI recognition are not connected.</p><label>Garment name<input autoFocus required maxLength="80" value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label><div className="form-row"><label>Category<select value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Color<input type="color" value={editor.color} onChange={e=>setEditor({...editor,color:e.target.value})}/></label></div><label>Style tags<input maxLength="160" value={editor.tags} onChange={e=>setEditor({...editor,tags:e.target.value})}/></label><div className="toolbar"><button className="primary" disabled={busy} type="submit">Save garment</button>{!editor.isNew && <><button type="button" onClick={()=>{openListing(editor);setEditor(null);}}>Resell</button><button type="button" onClick={()=>{if(save(markWorn(state,[editor.id])))setEditor({...editor,wears:editor.wears+1});}}>Worn +1 ({editor.wears})</button><button className="danger" type="button" onClick={()=>{if(confirm('Delete this garment and its photo from this browser?'))removeItem(editor.id);}}>Delete</button></>}</div></form></section></div>}
    {resale && <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="resale-title"><div className="section-heading"><h2 id="resale-title">A new-home starter kit.</h2><button aria-label="Close listing" onClick={()=>setResale(null)}>×</button></div><p>Edit your draft, then copy the text or export a JSON package with the stored photo.</p><label>Listing draft<textarea rows="13" value={resale.text} onChange={e=>setResale({...resale,text:e.target.value})}/></label><div className="toolbar"><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(resale.text);notify('Listing copied to clipboard.');}catch{notify('Clipboard unavailable. Select the text and copy manually.');}}}>Copy listing</button><button onClick={exportListing}>Export package ↓</button></div><p className="muted">Check brand, size, condition, price and photo before posting. Nothing is automatically published.</p></section></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
