import React from 'react';
import run from '../vision/results/wardrobe-rag-development.json';

export default function RagEvidence() {
  const crowded=run.retrievalChecks.find(c=>c.id==='crowded-closet-187');
  return <section className="panel rag-evidence">
    <p className="eyebrow">WARDROBE RETRIEVAL · LOCAL GENERATION</p><h2>From your brief to an owned outfit.</h2>
    <p>The stylist retrieves your saved garment details and relevant styling notes before generating a suggestion. Every returned look must use owned, reviewed pieces, form a complete outfit, and include your starting piece when selected.</p>
    <div className="rag-flow" aria-label="Outfit pipeline"><div><b>01</b><strong>Retrieve</strong><span>Keywords + local text embeddings, with keyword fallback</span></div><div><b>02</b><strong>Plan</strong><span>Complete combinations with your constraints</span></div><div><b>03</b><strong>Explain</strong><span>Local AI interpretation + saved source facts</span></div></div>
    <p>The current hybrid route combines keyword and text-embedding ranks, then preserves the pieces needed for a complete outfit. It falls back to keywords if embeddings are unavailable. The small trained reranker is a separate, optional development experiment.</p>
    <h3>Earlier keyword baseline</h3><p>The saved results below predate hybrid retrieval. They are retained for comparison and are not measurements of the new embedding pipeline.</p>
    <div className="pipeline-metrics"><div><span>Earlier requests with valid looks</span><strong>{run.summary.styleCasesPassed}/{run.summary.styleCases}</strong></div><div><span>Earlier large-closet retrieval check</span><strong>{crowded?.data.retrieval?.eligibleCount||'—'} → {crowded?.data.retrieval?.retrievedCount||'—'} pieces</strong></div><div><span>Earlier retrieval & rejection checks</span><strong>{run.summary.retrievalChecksPassed}/{run.summary.retrievalChecks}</strong></div></div>
    <div className="evidence-table-wrap"><table><thead><tr><th>Development request</th><th>Valid looks</th><th>Result</th><th>Request time</th></tr></thead><tbody>{run.cases.map(test=><tr key={test.id}><td>{test.query.context} · {test.query.anchorId==='photo-knit'?'sweater anchor':'blazer anchor'}</td><td>{test.data.data?.outfits.length||0}</td><td className={test.passed?'result-match':'result-review'}>{test.passed?'Constraints passed':'Needs work'}</td><td>{(test.totalMs/1000).toFixed(1)} s</td></tr>)}</tbody></table></div>
    <details className="pipeline-notes"><summary>What does the earlier evidence establish?</summary><p>Two briefs use the seven real-photo samples’ authored metadata. A separate test adds 180 distracting garment records; another checks rejection when shoes are missing. These checks establish the earlier API and constraint behavior, not fashion quality or recall on real user wardrobes.</p><p>That run used BM25 with explicit vocabulary expansion and no embeddings. The first integration run produced a valid sweater look but no valid blazer look; that failure is retained. Source facts are saved metadata, not proof that every AI explanation is correct.</p><p>Measured on {new Date(run.date).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}. Timings include local model runtime conditions. A larger, independently labeled brief set and wearer feedback remain necessary.</p></details>
  </section>;
}
